server:
  port: "8080"
  read_timeout: 15
  write_timeout: 15
  idle_timeout: 60
  shutdown_timeout: 10

database:
  dsn: "postgres://postgres:password@localhost:5432/postgres"

storage:
  root: "data"
  default_bucket: "files"
